apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.name }}
    version: {{ .Values.version }}
spec:
  ports:
    {{- if .Values.rest.enabled }}
  - port: {{ .Values.rest.port }}
    targetPort: {{ .Values.rest.targetPort }}
    protocol: {{ .Values.rest.protocol }}
    name: {{ .Values.rest.name}}
    {{- end }}
    {{- if .Values.grpc.enabled }}
  - port: {{ .Values.grpc.port }}
    targetPort: {{ .Values.grpc.targetPort }}
    protocol: {{ .Values.grpc.protocol }}
    name: {{ .Values.grpc.name }}
    {{- end }}
  selector:
    app: {{ .Values.name }}
    version: {{ .Values.service.version }}
