{{- if .Values.ingress.enabled }}
apiVersion: {{ .Values.ingress.api }}
kind: VirtualService
metadata:
  name: {{ .Values.name }}
spec:
  hosts:
    - "{{ .Values.ingress.hostname }}"
  gateways:
    - {{ .Values.ingress.gateway }}
  http:
  {{- if .Values.rest.enabled }}
  - match:
      - uri:
          prefix: {{ .Values.rest.matchprefix }}
    rewrite:
      uri: {{ .Values.rest.matchrewrite }}
    route:
      - destination:
          host: {{ .Values.name }}
          port:
            number: {{ .Values.rest.port }}
  {{- end }}
  {{- if .Values.grpc.enabled }}
  - match:
      - uri:
          prefix: {{ .Values.grpc.matchprefix }}
    route:
      - destination:
          host: {{ .Values.name }}
          port:
            number: {{ .Values.grpc.port }}
  {{- end }}
  {{- end }}